namespace Seq.Api.Model.Settings
{
    public enum SettingName
    {
        AutomaticAccessADGroup,
        AutomaticallyGrantUserAccessToADAccounts,
        AzureADClientId,
        AzureADClientKey,
        AzureADTenantId,
        BackupLocation,
        BackupsToKeep,
        BackupUtcTimeOfDay,
        CheckForPackageUpdates,
        CheckForUpdates,
        InstanceTitle,
        IsActiveDirectoryAuthentication,
        IsAuthenticationEnabled,
        LazilyFlushEventWrites,
        MasterKeyIsBackedUp,
        MinimumFreeStorageSpace,
        NewUserShowSignalIds,
        NewUserShowQueryIds,
        NewUserShowDashboardIds,
        RequireApiKeyForWritingEvents,
        RawEventMaximumContentLength,
        RawPayloadMaximumContentLength,
        ThemeStyles
    }
}
